# Generated by Django 4.1.2 on 2022-11-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDueño', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nombre dueño',
                'verbose_name_plural': 'Nombre dueños',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaterinariaAPP.dueno')),
            ],
            options={
                'verbose_name': 'Nombre mascota',
                'verbose_name_plural': 'Nombre mascotas',
            },
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAtencion', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('nombrePaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaterinariaAPP.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAtencion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('nombrePaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaterinariaAPP.mascota')),
            ],
            options={
                'verbose_name': 'nombre paciente',
                'verbose_name_plural': 'nombre pacientes',
            },
        ),
        migrations.CreateModel(
            name='Estetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAtencion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('nombrePaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaterinariaAPP.mascota')),
            ],
            options={
                'verbose_name': 'nombre paciente',
                'verbose_name_plural': 'nombre pacientes',
            },
        ),
        migrations.CreateModel(
            name='Cirugias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAtencion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('nombrePaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaterinariaAPP.mascota')),
            ],
            options={
                'verbose_name': 'nombre paciente',
                'verbose_name_plural': 'nombre pacientes',
            },
        ),
    ]
